[tool.poetry]
name = "python"
version = "3.7"
description = "Python version"
authors = ["Gaurav Gund <gaurav.gund@kindredgroup.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
